#!/usr/bin/env python3
"""
Font Conversion Tool for Typewrite OS

Converts TTF/OTF/WOFF2 fonts to a bitmap format usable by UEFI applications.
Uses FreeType for rendering, supporting all font formats.

Usage:
    python3 convert_font.py <input_font> <output_name> [size]

Example:
    python3 convert_font.py fonts/Virgil.woff2 virgil 24
    python3 convert_font.py fonts/Inter-Regular.ttf helvetica 24
"""

import sys
import os
import argparse
import struct
import freetype


def render_glyph(face, char, size):
    """
    Render a character to a bitmap using FreeType.
    Returns a tuple: (width, height, advance_width, bitmap_data)
    """
    # Load the glyph
    glyph_index = face.get_char_index(char)
    face.load_char(char, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
    
    glyph = face.glyph
    bitmap = glyph.bitmap
    
    # Get metrics
    width = bitmap.width
    height = bitmap.rows
    advance = int(glyph.advance.x / 65536)  # Convert 26.6 fixed point
    
    if width == 0:
        width = 1
    if height == 0:
        height = 1
    
    # Convert bitmap to packed format (1 bit per pixel)
    packed_data = []
    for row in range(height):
        byte = 0
        bit = 0
        for col in range(width):
            pixel_idx = row * bitmap.pitch + (col // 8)
            if pixel_idx < len(bitmap.buffer):
                if bitmap.buffer[pixel_idx] & (0x80 >> (col % 8)):
                    byte |= (1 << bit)
            bit += 1
            if bit == 8:
                packed_data.append(byte)
                byte = 0
                bit = 0
        if bit > 0:
            packed_data.append(byte)
    
    # Pad rows to at least 1 byte
    while len(packed_data) < ((width + 7) // 8) * height:
        packed_data.append(0)
    
    return width, height, advance, packed_data


def convert_font(input_file, output_name, size=24):
    """Convert a font file to C header format."""
    
    print(f"Loading font: {input_file}")
    face = freetype.Face(input_file)
    
    # Set size
    face.set_pixel_sizes(0, size)
    
    # Get font name
    font_name = output_name
    if face.family_name:
        font_name = face.family_name.decode('utf-8', errors='ignore')
    
    print(f"Font: {font_name}")
    print(f"Size: {size}px")
    
    # Generate glyphs for ASCII printable characters (32-126)
    glyphs = []
    
    for ascii_code in range(32, 127):
        char = chr(ascii_code)
        try:
            width, height, advance, bitmap = render_glyph(face, char, size)
            glyphs.append({
                'char': char,
                'ascii': ascii_code,
                'width': width,
                'height': height,
                'advance': advance,
                'bitmap': bitmap
            })
        except Exception as e:
            print(f"  Warning: Failed to render '{char}': {e}")
            # Use placeholder
            glyphs.append({
                'char': char,
                'ascii': ascii_code,
                'width': size // 2,
                'height': size,
                'advance': size // 2,
                'bitmap': [0] * ((size // 2 + 7) // 8 * size)
            })
    
    # Calculate metrics
    max_width = max(g['width'] for g in glyphs)
    max_height = max(g['height'] for g in glyphs)
    row_bytes = (max_width + 7) // 8
    
    print(f"Max glyph size: {max_width}x{max_height}")
    
    # Generate C header
    output_file = f"{output_name}.h"
    
    with open(output_file, 'w') as f:
        f.write(f"""/**
 * {output_name}.h - {font_name} bitmap font for Typewrite OS
 * 
 * Auto-generated by convert_font.py
 * Original font: {input_file}
 * Size: {size}px
 * 
 * Contains bitmap data for ASCII characters 32-126 (printable range)
 * Format: 1-bit per pixel, row-major, LSB first in each byte
 */

#ifndef {output_name.upper()}_H
#define {output_name.upper()}_H

#include <Uefi.h>

/* Font metadata */
#define {output_name.upper()}_SIZE       {size}
#define {output_name.upper()}_HEIGHT     {max_height}
#define {output_name.upper()}_MAX_WIDTH {max_width}
#define {output_name.upper()}_ROW_BYTES  {row_bytes}
#define {output_name.upper()}_ASC_MIN   32
#define {output_name.upper()}_ASC_MAX   126

""")
        
        # Write glyph offsets
        f.write(f"/* Glyph data offsets (one per ASCII character) */\n")
        f.write(f"static const UINT32 {output_name}_offsets[] = {{\n")
        offset = 0
        for g in glyphs:
            f.write(f"  {offset},  /* '{g['char']}' ({g['ascii']}) */\n")
            offset += len(g['bitmap'])
        f.write("};\n\n")
        
        # Write glyph widths
        f.write(f"/* Glyph widths */\n")
        f.write(f"static const UINT8 {output_name}_widths[] = {{\n")
        for g in glyphs:
            f.write(f"  {g['width']},  /* '{g['char']}' */\n")
        f.write("};\n\n")
        
        # Write glyph advance widths
        f.write(f"/* Glyph advance widths (horizontal spacing) */\n")
        f.write(f"static const UINT8 {output_name}_advances[] = {{\n")
        for g in glyphs:
            adv = min(int(g['advance']), 255)
            f.write(f"  {adv},  /* '{g['char']}' */\n")
        f.write("};\n\n")
        
        # Write bitmap data
        f.write(f"/* Glyph bitmap data (1-bit per pixel, row-major) */\n")
        f.write(f"static const UINT8 {output_name}_bitmap[] = {{\n")
        
        for g in glyphs:
            f.write(f"  /* '{g['char']}' ({g['ascii']}) - {g['width']}x{g['height']} */\n")
            for i in range(0, len(g['bitmap']), 16):
                chunk = g['bitmap'][i:i+16]
                hex_str = ','.join(f"0x{b:02x}" for b in chunk)
                f.write(f"  {hex_str},\n")
        
        f.write("};\n\n")
        
        # Write accessor function
        f.write(f"""/* Function to draw a character with this font */
VOID
DrawChar_{output_name} (
  IN EFI_GRAPHICS_OUTPUT_PROTOCOL *Gop,
  IN UINT32 X,
  IN UINT32 Y,
  IN CHAR16 Char,
  IN EFI_GRAPHICS_OUTPUT_BLT_PIXEL *FgColor
  );

#endif /* {output_name.upper()}_H */
""")
    
    print(f"Generated: {output_file}")
    
    # Also generate a simple binary file for embedding
    binary_file = f"{output_name}.bin"
    with open(binary_file, 'wb') as f:
        # Write header (24 bytes)
        f.write(struct.pack('<I', size))           # Font size
        f.write(struct.pack('<I', max_height))     # Max height
        f.write(struct.pack('<I', max_width))      # Max width
        f.write(struct.pack('<I', row_bytes))      # Bytes per row
        f.write(struct.pack('<I', 32))             # ASCII min
        f.write(struct.pack('<I', 126))            # ASCII max
        
        # Write offsets
        offset = 0
        for g in glyphs:
            f.write(struct.pack('<I', offset))
            offset += len(g['bitmap'])
        
        # Write widths
        for g in glyphs:
            f.write(struct.pack('<B', g['width']))
        
        # Write advances
        for g in glyphs:
            adv = min(int(g['advance']), 255)
            f.write(struct.pack('<B', adv))
        
        # Write bitmap data
        for g in glyphs:
            f.write(bytes(g['bitmap']))
    
    print(f"Generated: {binary_file}")
    print("Done!")
    
    return output_file, binary_file


def main():
    parser = argparse.ArgumentParser(description='Convert TTF/OTF/WOFF2 fonts to Typewrite OS bitmap format')
    parser.add_argument('input', help='Input font file (TTF, OTF, WOFF, or WOFF2)')
    parser.add_argument('output', help='Output name (without extension)')
    parser.add_argument('--size', '-s', type=int, default=24, help='Font size in pixels (default: 24)')
    
    args = parser.parse_args()
    
    if not os.path.exists(args.input):
        print(f"Error: Input file not found: {args.input}")
        sys.exit(1)
    
    convert_font(args.input, args.output, args.size)


if __name__ == '__main__':
    main()
