#!/usr/bin/env python3
"""Emit tic80-uefi/builtin_cart.inc — minimal raw .tic (CHUNK_DEFAULT + CHUNK_CODE)."""
import struct
import sys
from pathlib import Path

CHUNK_DEFAULT = 17
CHUNK_CODE = 5


def pack_chunk(typ: int, bank: int, size: int, payload: bytes = b"") -> bytes:
    w = (typ & 0x1F) | ((bank & 7) << 5) | ((size & 0xFFFF) << 8)
    return struct.pack("<I", w) + payload


CODE = b"""-- title: UEFI hello
-- script: lua

function TIC()
  cls(12)
  print('TIC-80 UEFI',40,52,15)
  print('arrows Z X A S',32,68,7)
end
"""


def main() -> None:
    cart = pack_chunk(CHUNK_DEFAULT, 0, 0) + pack_chunk(CHUNK_CODE, 0, len(CODE), CODE)
    out = Path(__file__).resolve().parent.parent / "builtin_cart.inc"
    lines = ["/* Generated by tools/gen_builtin_cart.py */", ""]
    lines.append("static const UINT8 tic80_builtin_cart[] = {")
    for i in range(0, len(cart), 12):
        chunk = cart[i : i + 12]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hexes},")
    lines.append("};")
    lines.append("")
    lines.append(f"#define tic80_builtin_cart_len  ({len(cart)}U)")
    lines.append("")
    out.write_text("\n".join(lines), encoding="ascii")
    print(f"Wrote {out} ({len(cart)} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
